---
#  DNS Settings
dns_domain_name: raft.lutris.house
dns_loadbalancer_ip: 172.16.58.253
dns_allow_transfer:
  - 172.16.0.0/18

#  Kubernetes settings
k8s_version: "1.34"
k8s_pod_cidr_ipv4: 10.160.0.0/12
k8s_pod_cidr_ipv6: "fd00:cbe:0::/56"
k8s_svc_cidr_ipv4: 10.128.0.0/16
k8s_svc_cidr_ipv6: "fd00:cbe:1::/112"
k8s_pod_cidr: "{{ k8s_pod_cidr_ipv4 }},{{ k8s_pod_cidr_ipv6 }}"
k8s_svc_cidr: "{{ k8s_svc_cidr_ipv4 }},{{ k8s_svc_cidr_ipv6 }}"
k8s_svc_dns: "polycule.{{ dns_domain_name }}"
k8s_api_name: "k8s-api.{{ dns_domain_name }}"
k8s_api_loadbalancer_ip: 172.16.58.11
k8s_svc_loadbalancer_ipv4: 172.16.60.1-172.16.60.200
k8s_svc_loadbalancer_ipv6: 2001:5a8:4bd5:ef00::f00d:cbe:0/112
k8s_all_worker_nodes: false

#  Service settings
letsencrypt_email: alice@tuxnami.org
forgejo_loadbanacer_ip: 172.16.60.200
forgejo_volume_size: 60Gi
monitoring_prometheus_volume_size: 20Gi
monitoring_alertmanager_volume_size: 5Gi
monitoring_grafana_volume_size: 5Gi
pihole_loadbalancer_ip: 172.16.60.53

#  Extra packages for managed nodes
extra_packages:
  - git
  - k9s
  - vim
  - mc
  - neovim
  - ipython
  - zsh
  - tmux
  - NetworkManager-tui
