---
k8s_version: "1.34"
k8s_pod_cidr_ipv4: 10.160.0.0/12
k8s_pod_cidr_ipv6: "fd00:cbe:0::/56"
k8s_svc_cidr_ipv4: 10.128.0.0/16
k8s_svc_cidr_ipv6: "fd00:cbe:1::/112"
k8s_pod_cidr: "{{ k8s_pod_cidr_ipv4 }},{{ k8s_pod_cidr_ipv6 }}"
k8s_svc_cidr: "{{ k8s_svc_cidr_ipv4 }},{{ k8s_svc_cidr_ipv6 }}"
k8s_svc_dns: k8s-test.raft.lutris.house
k8s_api_name: k8s-api.raft.lutris.house
