---
- name: Add prometheus repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    kubeconfig: /etc/kubernetes/admin.conf
  run_once: true

- name: install monitoring stack
  run_once: true
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    kubeconfig: /etc/kubernetes/admin.conf
    namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    values:
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
      grafana:
        persistence:
          enabled: true
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          size: 5Gi
      alertmanager:
        alertmanagerSpec:
          storage:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 5Gi

- name: monitoring certificate
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: monitoring-certificate
        namespace: monitoring
      spec:
        dnsNames:
          - grafana.raft.lutris.house
          - prometheus.raft.lutris.house
          - alertmanager.raft.lutris.house
        secretName: monitoring-certificate
        issuerRef:
          name: letsencrypt-dns01-issuer
          kind: ClusterIssuer

- name: monitornig gateway
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: monitoring-gateway
        namespace: monitoring
      spec:
        gatewayClassName: istio
        listeners:
          - name: http
            port: 443
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                from: Same
            tls:
              certificateRefs:
                - kind: Secret
                  group: ""
                  name: monitoring-certificate

- name: grafana route
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:

      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: grafana-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "grafana.raft.lutris.house"
        rules:
          - backendRefs:
              - name: prometheus-stack-grafana
                port: 80

- name: prometheus route
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: prometheus-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "prometheus.raft.lutris.house"
        rules:
          - backendRefs:
              - name: prometheus-stack-kube-prom-prometheus
                port: 9090

- name: alertmanager route
  run_once: true
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition:

      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: alertmanager-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "alertmanager.raft.lutris.house"
        rules:
          - backendRefs:
              - name: prometheus-stack-kube-prom-alertmanager
                port: 9093
