---
- name: Add prometheus repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: install monitoring stack
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    values:
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: "{{ monitoring_prometheus_volume_size }}"

      grafana:
        persistence:
          enabled: true
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          size: "{{ monitoring_grafana_volume_size }}"

      alertmanager:
        alertmanagerSpec:
          storage:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: "{{ monitoring_alertmanager_volume_size }}"

- name: monitoring certificate
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: monitoring-certificate
        namespace: monitoring
      spec:
        dnsNames:
          - "grafana.{{ dns_domain_name }}"
          - "prometheus.{{ dns_domain_name }}"
          - "alertmanager.{{ dns_domain_name }}"
        secretName: monitoring-certificate
        issuerRef:
          name: letsencrypt-dns01-issuer
          kind: ClusterIssuer

- name: monitornig gateway
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: monitoring-gateway
        namespace: monitoring
      spec:
        gatewayClassName: istio
        listeners:
          - name: http
            port: 443
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                from: Same
            tls:
              certificateRefs:
                - kind: Secret
                  group: ""
                  name: monitoring-certificate

- name: grafana route
  kubernetes.core.k8s:
    state: present
    definition:

      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: grafana-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "grafana.{{ dns_domain_name }}"
        rules:
          - backendRefs:
              - name: prometheus-stack-grafana
                port: 80

- name: prometheus route
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: prometheus-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "prometheus.{{ dns_domain_name }}"
        rules:
          - backendRefs:
              - name: prometheus-stack-kube-prom-prometheus
                port: 9090

- name: alertmanager route
  kubernetes.core.k8s:
    state: present
    definition:

      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: alertmanager-route
        namespace: monitoring
      spec:
        parentRefs:
          - name: monitoring-gateway
        hostnames:
          - "alertmanager.{{ dns_domain_name }}"
        rules:
          - backendRefs:
              - name: prometheus-stack-kube-prom-alertmanager
                port: 9093
