---
- name: Install dnsdist
  ansible.builtin.dnf5:
    name: dnsdist
    state: latest
- name: Copy config file
  ansible.builtin.template:
    src: dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
    owner: root
    group: dnsdist
    mode: 0640
- name: Start dnsdist service
  ansible.builtin.systemd_service:
    name: dnsdist
    enabled: true
    state: started
